name: "打卡"

# 触发条件
on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: "0 1 * * *"  # UTC 01:00 / 北京时间 09:00，运行 ywm.json
    - cron: "0 2 * * *"  # UTC 02:00 / 北京时间 10:00，运行 lzy.json
    - cron: "0 9 * * *"  # UTC 09:00 / 北京时间 17:00
    - cron: "0 10 * * *" # UTC 10:00 / 北京时间 18:00

# 并发控制，避免任务重叠
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 第一个任务：运行 ywm.json
  run-ywm:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 添加超时限制

    steps:
      # 设置时区
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"

      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 执行 ywm.json 配置的打卡任务
      - name: Run sign in script (ywm.json)
        env:
          USER: ${{ secrets.USER }}
          CONFIG_FILE: "user/ywm.json"  # 设置环境变量传入配置文件路径
          TZ: Asia/Shanghai
        run: |
          python main.py --config $CONFIG_FILE


  # 第二个任务：运行 lzy.json
  run-lzy:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 添加超时限制

    steps:
      # 设置时区
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"

      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 执行 lzy.json 配置的打卡任务
      - name: Run sign in script (lzy.json)
        env:
          USER: ${{ secrets.USER }}
          CONFIG_FILE: "user/lzy.json"  # 设置环境变量传入配置文件路径
          TZ: Asia/Shanghai
        run: |
          python main.py --config $CONFIG_FILE
